var hierarchy =
[
    [ "nabla::AnimatableComponent", "structnabla_1_1_animatable_component.html", null ],
    [ "nabla::AnimationSystem", "classnabla_1_1_animation_system.html", null ],
    [ "nabla::data::Color", "classnabla_1_1data_1_1_color.html", null ],
    [ "nabla::ComponentRegistry", "classnabla_1_1_component_registry.html", null ],
    [ "nabla::ConfigManager", "classnabla_1_1_config_manager.html", null ],
    [ "nabla::Entity", "structnabla_1_1_entity.html", null ],
    [ "nabla::EntityManager", "classnabla_1_1_entity_manager.html", null ],
    [ "nabla::renderer::Handle< Index, Version >", "classnabla_1_1renderer_1_1_handle.html", null ],
    [ "nabla::ComponentRegistry::Handle", "structnabla_1_1_component_registry_1_1_handle.html", null ],
    [ "HeapAllocator", "class_heap_allocator.html", null ],
    [ "nabla::data::IData", "classnabla_1_1data_1_1_i_data.html", [
      [ "nabla::data::Interger", "classnabla_1_1data_1_1_interger.html", null ]
    ] ],
    [ "nabla::renderer::IndexedVertexBuffer", "structnabla_1_1renderer_1_1_indexed_vertex_buffer.html", null ],
    [ "nabla::renderer::InitConfig", "structnabla_1_1renderer_1_1_init_config.html", null ],
    [ "nabla::LocalPoseComponent", "structnabla_1_1_local_pose_component.html", null ],
    [ "nabla::ModelData::Material", "structnabla_1_1_model_data_1_1_material.html", null ],
    [ "nabla::ModelData::Mesh", "structnabla_1_1_model_data_1_1_mesh.html", null ],
    [ "nabla::MeshStaticComponent", "structnabla_1_1_mesh_static_component.html", null ],
    [ "nabla::ModelData", "classnabla_1_1_model_data.html", null ],
    [ "PageAllocator", "class_page_allocator.html", null ],
    [ "PageAllocProxy< T >", "class_page_alloc_proxy.html", null ],
    [ "nabla::PolygonStaticComponent", "structnabla_1_1_polygon_static_component.html", null ],
    [ "nabla::Sampler", "classnabla_1_1_sampler.html", null ],
    [ "nabla::ServiceLocator", "classnabla_1_1_service_locator.html", null ],
    [ "Shader", "class_shader.html", null ],
    [ "nabla::SharableComponent< T >", "structnabla_1_1_sharable_component.html", null ],
    [ "nabla::SharableComponent< nabla::AnimatableComponent >", "structnabla_1_1_sharable_component.html", null ],
    [ "nabla::SharableComponent< nabla::LocalPoseComponent >", "structnabla_1_1_sharable_component.html", null ],
    [ "nabla::SkeletonComponent", "structnabla_1_1_skeleton_component.html", null ],
    [ "nabla::SlotAllocator< Increament >", "classnabla_1_1_slot_allocator.html", null ],
    [ "nabla::SlotAllocatorProxy< T, Increament >", "classnabla_1_1_slot_allocator_proxy.html", null ],
    [ "StaticDrawCall", "struct_static_draw_call.html", null ],
    [ "nabla::STLVectorEx< T, Alloc >", "classnabla_1_1_s_t_l_vector_ex.html", null ],
    [ "nabla::STLVectorEx< char >", "classnabla_1_1_s_t_l_vector_ex.html", null ],
    [ "nabla::STLVectorEx< Entity::entity_t >", "classnabla_1_1_s_t_l_vector_ex.html", null ],
    [ "nabla::STLVectorEx< float >", "classnabla_1_1_s_t_l_vector_ex.html", null ],
    [ "nabla::STLVectorEx< glm::vec2 >", "classnabla_1_1_s_t_l_vector_ex.html", null ],
    [ "nabla::STLVectorEx< glm::vec3 >", "classnabla_1_1_s_t_l_vector_ex.html", null ],
    [ "nabla::STLVectorEx< nabla::AnimatableComponent >", "classnabla_1_1_s_t_l_vector_ex.html", null ],
    [ "nabla::STLVectorEx< nabla::Entity >", "classnabla_1_1_s_t_l_vector_ex.html", null ],
    [ "nabla::STLVectorEx< nabla::LocalPoseComponent >", "classnabla_1_1_s_t_l_vector_ex.html", null ],
    [ "nabla::STLVectorEx< nabla::ModelData::Mesh >", "classnabla_1_1_s_t_l_vector_ex.html", null ],
    [ "nabla::STLVectorEx< unsigned int >", "classnabla_1_1_s_t_l_vector_ex.html", null ],
    [ "nabla::STLVectorEx< void * >", "classnabla_1_1_s_t_l_vector_ex.html", null ],
    [ "TypeId", "class_type_id.html", null ],
    [ "nabla::UndeletablePtrHandle< T >", "structnabla_1_1_undeletable_ptr_handle.html", null ],
    [ "nabla::UndeletablePtrHandle< nabla::AnimatableComponent >", "structnabla_1_1_undeletable_ptr_handle.html", null ],
    [ "nabla::UndeletablePtrHandle< nabla::LocalPoseComponent >", "structnabla_1_1_undeletable_ptr_handle.html", null ],
    [ "nabla::renderer::VertexBuffer", "structnabla_1_1renderer_1_1_vertex_buffer.html", null ],
    [ "nabla::renderer::Window", "classnabla_1_1renderer_1_1_window.html", null ]
];